# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
latex: false
pandoc: false

matrix:
  include:
    - os: linux
      r: oldrel
    - os: linux
      r: release
    - os: linux
      r: devel
    - os: osx
      r: release
      brew_packages: libgit2
  allow_failures:
    - os: osx

env:
  global:
    - R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
    - _R_CHECK_SYSTEM_CLOCK_=FALSE
    - _R_CHECK_FORCE_SUGGESTS_=FALSE

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo chown -R $(whoami) /usr/local/share; fi

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then Rscript -e 'if (getRversion() < numeric_version("3.6")) remotes::install_version("gridSVG", version = "1.6-0")'; fi

after_success:
  - Rscript -e 'covr::codecov()'
